import type { FeedItem } from "./types";

export const MOCK_FEED: FeedItem[] = [
  {
    id: "t1",
    type: "tweet",
    published_at: "2026-04-03T14:22:00Z",
    author_name: "Ignas | DeFi",
    author_handle: "DefiIgnas",
    text: "USD stablecoin yields are compressing hard.\n\nAave USDC on Ethereum: 3.1%\nMorpho USDC vaults: 4.8%\nFluid USDT: 5.2%\n\nMeanwhile sUSDS is sitting at 6.5% with zero IL risk. The Maker flywheel is real.",
    likes: 842,
    retweets: 156,
    url: "https://x.com/DefiIgnas/status/example1",
  },
  {
    id: "a1",
    type: "article",
    published_at: "2026-04-03T11:00:00Z",
    source: "Today in DeFi",
    title: "ETH Staking Yields: Who's Winning After Pectra?",
    excerpt:
      "Post-Pectra validator economics are shifting. Lido's stETH yield has stabilized around 3.2%, while Rocket Pool's rETH edges higher at 3.4%. But the real story is the restaking layer — EigenLayer-adjacent protocols are offering 5-8% on top of base staking rewards.",
    author: "Gabe Tramble",
    read_time_min: 6,
    url: "https://todayindefi.com/eth-staking-pectra",
  },
  {
    id: "s1",
    type: "substack",
    published_at: "2026-04-03T08:30:00Z",
    publication: "Dose of DeFi",
    author: "Chris Powers",
    title: "RWA Yields Are Eating DeFi's Lunch",
    excerpt:
      "BlackRock's BUIDL fund is now the largest tokenized treasury product at $1.2B. Ondo's USDY crossed $400M. The message is clear: institutional money wants on-chain yield, but they want it backed by T-bills, not governance tokens. Here's what that means for native DeFi yields.",
    url: "https://doseofdefi.substack.com/p/rwa-yields-eating-defi",
  },
  {
    id: "t2",
    type: "tweet",
    published_at: "2026-04-02T22:15:00Z",
    author_name: "Hamz",
    author_handle: "0xHamz",
    text: "Morpho vault meta is underrated.\n\nCurators compete to offer the best risk-adjusted yield. You get Aave-like simplicity with market-level granularity underneath.\n\nThe USDC Gauntlet vault on Base is doing 5.8% with only blue-chip collateral markets. That's the sweet spot.",
    likes: 1203,
    retweets: 289,
    url: "https://x.com/0xHamz/status/example2",
  },
  {
    id: "a2",
    type: "article",
    published_at: "2026-04-02T15:00:00Z",
    source: "The Defiant",
    title: "Yield Farming in 2026: Risk-Adjusted Returns Matter More Than APY",
    excerpt:
      "The era of chasing 4-digit APYs is over. Sophisticated LPs are now evaluating organic yield ratio, contract age, and incentive runway before committing capital. We surveyed 50 DeFi power users on their yield evaluation framework.",
    author: "Samuel Haig",
    read_time_min: 8,
    url: "https://thedefiant.io/yield-farming-2026-risk-adjusted",
  },
  {
    id: "t3",
    type: "tweet",
    published_at: "2026-04-02T12:45:00Z",
    author_name: "Sassal",
    author_handle: "sassal0x",
    text: "ETH yield stack for the risk-averse:\n\n1. Stake ETH → wstETH (3.2% base)\n2. Supply wstETH on Aave → borrow USDC\n3. Deposit USDC in Fluid → 5.2%\n\nNet APR after borrow cost: ~4.8% on your ETH\n\nNo IL, no governance token exposure, battle-tested contracts only.",
    likes: 2156,
    retweets: 412,
    url: "https://x.com/sassal0x/status/example3",
  },
  {
    id: "s2",
    type: "substack",
    published_at: "2026-04-02T09:00:00Z",
    publication: "Yield Farming 101",
    author: "DeFi Dad",
    title: "The Stablecoin Yield Landscape: Q2 2026 Update",
    excerpt:
      "Every quarter I map out the full stablecoin yield landscape across Ethereum, Arbitrum, and Base. This edition covers 47 opportunities ranging from 2.1% (Aave DAI) to 12.4% (incentivized Aerodrome USDC-USDT). Spoiler: the risk-free rate has dropped below 4% for the first time since 2024.",
    url: "https://yieldfarming101.substack.com/p/stablecoin-yields-q2-2026",
  },
  {
    id: "t4",
    type: "tweet",
    published_at: "2026-04-01T19:30:00Z",
    author_name: "Mika Honkasalo",
    author_handle: "mikahonkasalo",
    text: "Base is quietly becoming the best chain for stablecoin yields.\n\nAerodrome USDC-USDT: 8.2%\nMoonwell USDC lending: 4.1%\nMorpho USDC vaults: 5.5%\n\nLower gas, same security model as Ethereum. The LP migration is happening.",
    likes: 675,
    retweets: 134,
    url: "https://x.com/mikahonkasalo/status/example4",
  },
  {
    id: "a3",
    type: "article",
    published_at: "2026-04-01T13:00:00Z",
    source: "Bankless",
    title: "Why Organic Yield Is the Only Yield That Matters",
    excerpt:
      "Incentive programs come and go. The protocols that generate real revenue — trading fees, lending interest, liquidation income — are the ones offering sustainable yield. We break down how to identify organic vs. mercenary yield and why it matters for your portfolio.",
    author: "David Hoffman",
    read_time_min: 10,
    url: "https://bankless.com/organic-yield-only-yield-that-matters",
  },
  {
    id: "t5",
    type: "tweet",
    published_at: "2026-04-01T08:15:00Z",
    author_name: "Flip Research",
    author_handle: "FlipResearch",
    text: "Unpopular opinion: the best yield strategy right now is the simplest.\n\nsUSDS → 6.5% APR\nNo smart contract risk beyond MakerDAO\nNo IL\nNo lockup\nLiquid\n\nSometimes the boring play is the right play.",
    likes: 1847,
    retweets: 321,
    url: "https://x.com/FlipResearch/status/example5",
  },
  {
    id: "s3",
    type: "substack",
    published_at: "2026-03-31T10:00:00Z",
    publication: "The DeFi Report",
    author: "Michael Nadeau",
    title: "Liquidity Mining Is Dead. Long Live Real Yield.",
    excerpt:
      "We tracked $2.3B in liquidity mining incentives distributed in Q1 2026. 68% of that capital left within 30 days of campaign end. The data is clear: mercenary capital chases incentives, not protocols. Here's how the best protocols are building sticky liquidity without token emissions.",
    url: "https://thedefireport.substack.com/p/liquidity-mining-dead-real-yield",
  },
  {
    id: "a4",
    type: "article",
    published_at: "2026-03-30T14:00:00Z",
    source: "DeFi Pulse",
    title: "Arbitrum Yield Opportunities: A Deep Dive Into Camelot and GMX",
    excerpt:
      "Arbitrum remains a top destination for yield seekers. Camelot's spNFT model offers concentrated liquidity with boosted rewards, while GMX's GLP alternative — GM pools — provide delta-neutral yield from perp trading fees. We compare risk-adjusted returns across both.",
    author: "Scott Lewis",
    read_time_min: 7,
    url: "https://defipulse.com/arbitrum-camelot-gmx-yield",
  },
  {
    id: "t6",
    type: "tweet",
    published_at: "2026-03-30T06:00:00Z",
    author_name: "rektdiomedes",
    author_handle: "rabordeaux",
    text: "BTC yield is finally real.\n\ncbBTC on Aave: 0.8% (lending)\nWBTC-cbBTC on Curve: 2.1% (trading fees)\ntBTC in Morpho: 1.9% (vault strategy)\n\nNot life-changing numbers but these are ORGANIC yields on BTC. No ponzi, no lockup. Two years ago this didn't exist.",
    likes: 934,
    retweets: 187,
    url: "https://x.com/rabordeaux/status/example6",
  },
];
